version: "3.9"
services:

  nginx:
    image: ${NGINX}
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - TZ=${TZ}
    volumes:
      - ${WORK_PATH}:${CONTAINER_WORK_PATH}:rw
      - ${NGINX_CONFIG_DIR}:/etc/nginx/conf.d:ro
    networks:
      - dnmp

  php:
    image: ${PHP_MASTER}
    restart: unless-stopped
    container_name: php8
    volumes:
      - ${WORK_PATH}:${CONTAINER_WORK_PATH}:rw
    depends_on:
      - nginx
    networks:
      - dnmp
  
  mysql:
    image: ${MYSQL}
    container_name: mysql
    restart: unless-stopped
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${MYSQL_DATA_STORE}:/var/lib/mysql:rw
    command:
      --default-authentication-plugin=${DEFAULT_AUTHENTICATION_PLUGIN}
      --character-set-server=${CHARACTER_SET_SERVER}
      --collation-server=${COLLATION_SERVER}
      --explicit_defaults_for_timestamp=${EXPLICIT_DEFAULTS_FOR_TIMESTAMP}
      --default-storage-engine=${DEFAULT_STORAGE_ENGINE}
      --sql_mode=${SQL_MODE}
    networks:
      - dnmp

  redis:
    image: ${REDIS}
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - TZ=${TZ}
    volumes:
      - ${REDIS_CONFIG_DIR}:/usr/local/etc/redis/redis.conf:rw
      - ${REDIS_DATA_STORE}:/data
      - ${REDIS_LOG_FILE}:/var/log/redis.log:rw
    networks:
      - dnmp

networks:
  dnmp: